https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/

# **Univariate LSTM Models: Vanilla LSTM**

*The first two blocks are examples of data preparation*

In [ ]:
###Data Preparation

[10, 20, 30, 40, 50, 60, 70, 80, 90] #a univariate sequence

[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [ ]:
X = [10, 20, 30,
    20, 30, 40,
    30, 40, 50]

y = [40, 50, 60]


In [ ]:
###split_sequence() function =
###above behaviour =
### if n_steps are chosen as 3 then three numbers are selected as inputs and the fourth number is selected as output and again this repeated

def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [ ]:
### import libraries for univariate

from numpy import array

# univariate lstm example
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

In [ ]:
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


Vanilla LSTM: an LSTM model that has a single hidden layer of LSTM units, and an output layer used to make a prediction

In [ ]:
#a Vanilla LSTM for univariate time series forecasting
# define model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

A model with *50 LSTM units in the hidden layer* and an *output layer that predicts a single numerical value*.
The model is fit using the efficient Adam version of *stochastic gradient descent* and *optimised* using the *mean squared error*, or *‘mse‘ loss function*.

In [ ]:
# fit model
model.fit(X, y, epochs=200, verbose=0) #epoch: the number of complete passes through the training dataset

In [ ]:
# demonstrate prediction
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat) #the model predicts the next value in the sequence

[[103.2039]]
